---
- name: Create BusyBox Data Container
  docker_container:
    name: '{{data_container_name}}'
    image: busybox
    state: started
    tty: true
    volumes:
      - /data # Mount an empty volume to /data in the busybox container

  tags:
    - storage
