---
- block:
    - name: Run yolo client docker container
      docker_container:
        name: '{{client_container_name}}'
        image: '{{client_image_name}}'
        state: started
        volumes_from:
          - '{{data_container_name}}'
        ports:
          - '{{frontend_port}}'
        networks:
          - name: yolo_network
        network_mode: bridge
        env:
          CHOKIDAR_USEPOLLING: 'true'
          stdin_open: 'true'
        tty: true
      tags:
        - frontend
  when: ansible_os_family == 'Debian'
  rescue:
    - name: Handle error during client dockerization setup
      debug:
        msg: 'Client dockerization setup failed. Please check the logs.'
