---
- block:
    - name: Ensure backend  folder exists.
      stat:
        path: '{{playbook_dir}}/backend'
      register: backend_folder

    - name: Build yolo backend docker image
      docker_image:
        name: '{{backend_image_name}}'
        source: build
        build:
          path: '{{playbook_dir}}/backend'
      register: backend_image
      tags:
        - backend
    - name: Run yolo backend docker container
      docker_container:
        name: '{{backend_container_name}}'
        image: '{{backend_image_name}}'
        state: started
        volumes:
          - ./backend:/app/backend/
          - ./backend:/data/backend # also map to the data container
        ports:
          - '{{backend_port}}'
        networks:
          - name: yolo_network
        env:
          MONGO_URI: '{{db_url}}'
      tags:
        - backend

  when: backend_folder.stat.isdir is defined and backend_folder.stat.isdir
  rescue:
    - name: Handle error during backend dockerization setup
      debug:
        msg: 'Backend dockerization setup failed. Please check the logs.'
