---
- name: Build yolo backend docker image
  docker_image:
    name: yolo-backend
    path: '{{playbook_dir}}/backend'
    dockerfile: '{{playbook_dir}}/backend/Dockerfile'
  register: backend_image
