---
- name: Build yolo backend docker image
  docker_image:
    name: simonokello/yolo-backend:1.0.0
    source: build
    build:
      path: '{{playbook_dir}}/backend'
  register: backend_image

- name: Run yolo backend docker container
  docker_container:
    name: yolo-backend-container
    image: simonokello/yolo-backend:1.0.0
    state: started
    volumes:
      - ./backend:/app/backend/
      - ./backend:/data/backend # also map to the data container
    ports:
      - '5000:5000'
    networks:
      - name: yolo_network
    network_mode: bridge
    env:
      MONGO_URI: mongodb://yolo-database-container:27017/yolomy
